### ISSUE TITLE
Build fails with NoSuchMethodError

### ISSUE THREAD

**Issue by Plastix** [trbnb/MvvmBase#1]
I've been trying to set up Kotlin, Dagger (2.6), and Databinding in a personal project of mine yet my build won't complete successfully.

I came across your project and I noticed that your build fails as well: `./gradlew assembleDebug`.
I get

```
* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.NoSuchMethodError: com.google.common.collect.FluentIterable.append(Ljava/lang/Iterable;)Lcom/google/common/collect/FluentIterable;
```

Any ideas?

**Comment by trbnb** [comment]
I remember that message from other projects. I'm not too sure though how I solved it. IIRC it had something to do with either the Android build tools for Gradle or the Gradle wrapper. Have you tried:
- Setting the Android build tools version to 2.1.3

and/or
- Setting the Gradle wrapper version to 2.14.1 or 3.0?

**Comment by Plastix** [comment]
Thanks for the quick response! Unfortunately I tried Android Build Tools `2.1.3` and/or Gradle `2.14`/`2.14.1` and it didn't fix the problem.

**Comment by trbnb** [comment]
I don't have time tonight but I will try to look into this tomorrow.

**Comment by trbnb** [comment]
I took some time over the weekend to look at it and for me it built just fine. No matter the versions mentioned above. This tells me that there might be an issue with another influence, not the project itself. 
Have you had this problem with other projects as well?

**Comment by Plastix** [comment]
Yes. I'm not sure what is different about my system. I'll close this then.
