### ISSUE TITLE
Idea: Shared ViewModels

### ISSUE THREAD

**Issue by Tetr4** [trbnb/MvvmBase#11]
Hi guys,

Google recommends using a shared Viewmodel for communication between fragments:
https://developer.android.com/topic/libraries/architecture/viewmodel#share-data-between-fragments
For example a list fragment (master) and an item fragment (detail) may obtain a reference for the same `SelectionViewModel`, so the list can change the selection, which updates the detail fragment. Or multiple fragments in a wizard-like user registration flow, may write to the same `UserDataViewModel` like a blackboard.
Shared viemodels can be nicely scoped via the `viewModelStore` of the fragments' parent activity (or parent fragment):
```kotlin
// in child fragments
val sharedStore = requireActivity().viewModelStore
// returns already created viewmodel from store or creates a new one if no old viewmodel exists
val sharedViewModel = ViewModelProvider(sharedStore, factory)[SharedViewModel::class.java]
```

I think it would be a good idea to integrate some support for shared viewmodels in MvvmBase. Not sure how to cleanly integrate it with the existing architecture, as it is always one viewmodel per fragment. Maybe adding shared Viewmodels to the fragments main viewmodel? What do you think?

**Comment by trbnb** [comment]
Sorry that it took so long but the more I think about it the less it makes sense. I can't see a use case where this would really be THE solution.

**Comment by Tetr4** [comment]
Currently I use a helper extension function similar to this:
```kotlin
inline fun <reified VM : BaseViewModel> Fragment.sharedViewModel(
    provider: Provider<VM>,
    scope: ViewModelStoreOwner = requireActivity()
): VM {
    // factory that creates injected viewmodel
    val factory = object : ViewModelProvider.Factory {
        override fun <V : ViewModel> create(modelClass: Class<V>): V {
            @Suppress("UNCHECKED_CAST")
            return provider.get() as V
        }
    }
    // get viewmodel that is shared by the scope, e.g. all fragments in an activity
    // it will be newly created if no old one exists
    return ViewModelProvider(scope.viewModelStore, factory)[VM::class.java]
}
```
It's also possible to add more logic to support events or a property-change-listener.

Usage:
```kotlin
class MyFragment : MvvmFragment<MyViewModel>() {
    override val layoutId = R.layout.my_fragment
    override val viewModelProvider = Provider {
        // shared data binding viewmodel
        sharedViewModel(appComponent.myViewModelProvider)
    }

    override fun onViewModelLoaded(viewModel: MyViewModel) {
        // shared viewmodel from other fragment or standalone viewmodel
        val otherViewModel = sharedViewModel(appComponent.otherViewModelProvider)
    }
```

It really helps with communication and synchronization between fragments, especially if using single activity architecture. Maybe we can use this as an extension to the base library, like the command library :)

**Comment by trbnb** [comment]
Actually the command library is deprecated as it is integrated into this lib.

But to get back to the point: I'm not sure I understand what information you want to synchronize between your fragments. Could you give an example?

**Comment by Tetr4** [comment]
For example a fragment for a user profile and a fragment for editing this profile may share the same "ProfileViewModel", with mutable user data properties (name, address, etc.).
Or a map fragment with an infopanel fragment ([bottomsheet](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F11OfhrcSIkQmfj8wHMN4___5jdIjQUIkY%2Fanatomy-contents-partial.png)) may access the panel's viewmodel to change its data.

**Comment by trbnb** [comment]
> For example a fragment for a user profile and a fragment for editing this profile may share the same "ProfileViewModel", with mutable user data properties (name, address, etc.).  

Ah, I think I misunderstood the initial question. The scenario you described here should already be possible as two different view components (e.g. Fragments) can have the same ViewModel _class_. Sharing the _instance_ is a dependency injection issue though.

> Or a map fragment with an infopanel fragment (bottomsheet) may access the panel's viewmodel to change its data.  

Sounds like the panel should just have the same ViewModel as the map fragment.

**Comment by Tetr4** [comment]
> Sounds like the panel should just have the same ViewModel as the map fragment.

Yes, unless the panel is used somewhere else, i.e. it's a general component that is not only bound to the map. You would have to combine every component that accesses the panel into one giant viewmodel.

Like you mentioned, you can provide the same instance via DI, because keeping two instances state synchronized, especially with two way databinding, is not nice.
Providing a single instance is a bit tricky though, because the lifetime is also handled by the fragment's viewmodel store, which leads to issues with `onDestroy/onCleared` being called, even though the viewmodel is still used. However I just found a clean solution that already works with the base library. I just use the single activity's viewmodel store in fragments:
```kotlin
class MyFragment : MvvmFragment<MyViewModel>() {
    override val layoutId = R.layout.my_fragment
    override val viewModelProvider by lazy { appComponent.myViewModelProvider }
    override fun getViewModelStore() = requireActivity().viewModelStore // shared vm
}
```

Seems like using shared viewmodels is possible with the base library. Setting up property callbacks and events is a bit cumbersome, but also works. Maybe I will add a PR for another small sample app that showcases shared viewmodels :)

**Comment by trbnb** [comment]
I feel like this issue could be more easily solved by having some sort of business logic that is shared between the ViewModels. But I've never really run into this problem so if you have a good solution I'm open for a PR. :)
