### ISSUE TITLE
Events not working in fragments

### ISSUE THREAD

**Issue by Tetr4** [trbnb/MvvmBase#12]
`MvvmFragment::onEvent` is not being called when the viewmodel sends an event via the event channel. When manually adding a listener to the channel it works, but only via a lambda or variable reference:
```kotlin
viewModel.eventChannel.addListener { Log.d(event, "$it" }
```
When passing the method directly it does not work:
```kotlin
viewModel.eventChannel.addListener(this::onEvent)
```
I think the bug may be in `MvvmBindingFragment`. `viewModel.eventChannel.addListener(::onEvent)` is called instead of `viewModel.eventChannel.addListener(eventListener)`.

**Comment by trbnb** [comment]
That's exactly right. I've encountered this issue already and it will be fixed in the next release.

**Comment by Tetr4** [comment]
Nice, thanks 😄

**Comment by trbnb** [comment]
It took a while, but it's fixed and released.
