### ISSUE TITLE
Android X fragment onAttach

### ISSUE THREAD

**Issue by apm-christian-dziuba** [trbnb/MvvmBase#13]
the onAttach(context: Context?) changed to onAttach(@NonNull context: Context)

During compiling the app every fragment throws the following error: 

`
Accidental override: The following declarations have the same JVM signature (onAttach(Landroid/content/Context;)V):
    fun onAttach(p0: Context): Unit defined in de.appmotion.baseapp.gui.MyFragment
    fun onAttach(context: Context?): Unit defined in de.appmotion.baseapp.gui.MyFragment
`

**Comment by trbnb** [comment]
Fixed and released with 1.3.0.
