### ISSUE TITLE
feature request: show usage of fragments

### ISSUE THREAD

**Issue by BaN4NaJ0e** [trbnb/MvvmBase#3]
Can you expand the example code to fragments inside an activity. Like the current structure in our c4c base app.

**Comment by trbnb** [comment]
Yes. This is actually something I planned on doing before. I will try and see if I have time for it tonight.

**Comment by trbnb** [comment]
I added an example via this commit: c90abeaa8fb3551e113be2d1f42cc6b5252ef7b6.
