### ISSUE TITLE
loaderID could be simplified

### ISSUE THREAD

**Issue by BaN4NaJ0e** [trbnb/MvvmBase#7]
Instead of manually setting the loader id in each MvvmFragment or MvvmActivity this could be replaced by a random number. It this a valid approach?

instead of
`
    override val loaderID: Int
        get() = 42
`
you could write
`    override val loaderID: Int
        get() = UUID.randomUUID().hashCode()`

**Comment by trbnb** [comment]
That is a horrible approach, for multiple reasons.

1. Using random numbers might lead to reoccurring numbers for Fragments in the same Activity.
2. Using the getter in your example would lead to generating a new loader ID every time it is called.

**Edit:** 
What I see that could work is some sort of store or generator that generates loader IDs.
